// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Mon Jun 10 21:25:05 2019

AudioPin AudioPin_inst
(
	.CLOCK_50(CLOCK_50_sig) ,	// input  CLOCK_50_sig
	.SW(SW_sig) ,	// input [17:17] SW_sig
	.SW(SW_sig) ,	// input [15:0] SW_sig
	.KEY(KEY_sig) ,	// input [3:3] KEY_sig
	.KEY(KEY_sig) ,	// input [0:0] KEY_sig
	.readdata(readdata_sig) ,	// output [31:0] readdata_sig
	.AUD_BCLK(AUD_BCLK_sig) ,	// output  AUD_BCLK_sig
	.AUD_DACLRCK(AUD_DACLRCK_sig) ,	// output  AUD_DACLRCK_sig
	.AUD_ADCDAT(AUD_ADCDAT_sig) 	// output  AUD_ADCDAT_sig
);

